// file generated by the Paraglide-Next init command
import { PrefixStrategy, Navigation, Middleware } from "@inlang/paraglide-next";
import type { AvailableLanguageTag } from "@/paraglide/runtime";

export const strategy = PrefixStrategy<AvailableLanguageTag>({
  prefixDefault: "never",
  pathnames: {
    "/projekty": {
      pl: "/projekty",
      en: "/projects",
    },
    "/projekty/[slug]": {
      pl: "/projekty/[slug]",
      en: "/projects/[slug]",
    },
  },
  exclude: (pathname) => pathname === "/api" || pathname.startsWith("/api/"),
});

export const middleware = Middleware({ strategy });
export const { Link, useRouter, usePathname, redirect, permanentRedirect } =
  Navigation({ strategy });
